models:
  - name: stg_olist_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
  - name: stg_olist_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
  - name: stg_olist_order_items
    columns:
      - name: order_id
        tests: [not_null]
  - name: stg_olist_payments
    columns:
      - name: order_id
        tests: [not_null]