version: 2
models:
  - name: monthly_revenue
    columns:
      - name: month
        tests: [not_null, unique]
      - name: revenue
        tests: [not_null]
  - name: cancellation_rate
    columns:
      - name: month
        tests: [not_null, unique]
      - name: cancellation_rate
        tests: [not_null]
  - name: top_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: total_spend
        tests: [not_null]